# Generated by Django 4.2.7 on 2025-08-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('sales_manager', 'Sales Manager'), ('sales_rep', 'Sales Representative'), ('viewer', 'Viewer')], default='sales_rep', max_length=20)),
                ('permissions', models.JSONField(default=dict, help_text='Custom permissions for this user')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('US/Eastern', 'Eastern Time'), ('US/Central', 'Central Time'), ('US/Mountain', 'Mountain Time'), ('US/Pacific', 'Pacific Time'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris'), ('Asia/Tokyo', 'Tokyo'), ('Asia/Shanghai', 'Shanghai')], default='UTC', max_length=50)),
                ('google_calendar_connected', models.BooleanField(default=False)),
                ('outlook_calendar_connected', models.BooleanField(default=False)),
                ('calendar_sync_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('debriefing_reminders', models.BooleanField(default=True)),
                ('meeting_alerts', models.BooleanField(default=True)),
                ('ai_coaching_enabled', models.BooleanField(default=True)),
                ('auto_debriefing_scheduling', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'), models.Index(fields=['user'], name='user_profil_user_id_fbe33d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('meeting_view', 'Meeting Viewed'), ('debriefing_start', 'Debriefing Started'), ('debriefing_complete', 'Debriefing Completed'), ('lead_update', 'Lead Updated'), ('crm_sync', 'CRM Sync'), ('calendar_sync', 'Calendar Sync'), ('settings_change', 'Settings Changed')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_activi_user_id_c742e0_idx'), models.Index(fields=['activity_type', 'created_at'], name='user_activi_activit_1c12f9_idx'), models.Index(fields=['entity_type', 'entity_id'], name='user_activi_entity__08d33e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('exchange', 'Exchange Server')], max_length=20)),
                ('provider_user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('expired', 'Token Expired')], default='disconnected', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('next_sync', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=15)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_integrations',
                'indexes': [models.Index(fields=['user', 'status'], name='calendar_in_user_id_e9d5ae_idx'), models.Index(fields=['provider', 'status'], name='calendar_in_provide_a8863e_idx'), models.Index(fields=['next_sync'], name='calendar_in_next_sy_9cbefc_idx')],
                'unique_together': {('user', 'provider', 'provider_email')},
            },
        ),
    ]
