services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: meeting_intelligence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - C:\Users\Lenovo\Downloads\creatio-project-403207-6ee153e42fb2.json:/app/credentials/google_calendar_credentials.json:ro
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_CALENDAR_CREDENTIALS_FILE=/app/credentials/google_calendar_credentials.json
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A meeting_intelligence worker -l info
    volumes:
      - .:/app
      - C:\Users\Lenovo\Downloads\creatio-project-403207-6ee153e42fb2.json:/app/credentials/google_calendar_credentials.json:ro
    environment:
      - DEBUG=True
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_CALENDAR_CREDENTIALS_FILE=/app/credentials/google_calendar_credentials.json
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A meeting_intelligence beat -l info
    volumes:
      - .:/app
      - C:\Users\Lenovo\Downloads\creatio-project-403207-6ee153e42fb2.json:/app/credentials/google_calendar_credentials.json:ro
    environment:
      - DEBUG=True
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_CALENDAR_CREDENTIALS_FILE=/app/credentials/google_calendar_credentials.json
    depends_on:
      - db
      - redis

volumes:
  postgres_data: