# Generated by Django 4.2.7 on 2025-08-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debriefings', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debriefingsession',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debriefing', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='debriefingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debriefingquestion',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debriefings.debriefingquestion'),
        ),
        migrations.AddField(
            model_name='debriefingquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='debriefings.debriefingsession'),
        ),
        migrations.AddField(
            model_name='debriefinginsight',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='debriefings.debriefingsession'),
        ),
        migrations.AddField(
            model_name='debriefinginsight',
            name='source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debriefings.debriefingquestion'),
        ),
        migrations.AddIndex(
            model_name='debriefingtemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='debriefing__templat_053f45_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefingtemplate',
            index=models.Index(fields=['created_by'], name='debriefing__created_95749d_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefingsession',
            index=models.Index(fields=['meeting'], name='debriefing__meeting_4444d4_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefingsession',
            index=models.Index(fields=['user', 'status'], name='debriefing__user_id_e9cda2_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefingsession',
            index=models.Index(fields=['scheduled_time'], name='debriefing__schedul_29c9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefingsession',
            index=models.Index(fields=['status', 'scheduled_time'], name='debriefing__status_7c0061_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefingquestion',
            index=models.Index(fields=['session', 'question_order'], name='debriefing__session_0a114d_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefingquestion',
            index=models.Index(fields=['question_type'], name='debriefing__questio_44d1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefingquestion',
            index=models.Index(fields=['processed'], name='debriefing__process_92a795_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefinginsight',
            index=models.Index(fields=['session', 'insight_type'], name='debriefing__session_c44e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefinginsight',
            index=models.Index(fields=['confidence_level'], name='debriefing__confide_d2877a_idx'),
        ),
        migrations.AddIndex(
            model_name='debriefinginsight',
            index=models.Index(fields=['user_validated'], name='debriefing__user_va_818adb_idx'),
        ),
    ]
