# Generated by Django 4.2.7 on 2025-08-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('owner', models.CharField(help_text='Can be internal user or external contact', max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('is_commitment', models.BooleanField(default=False, help_text='True if this is a commitment made to customer')),
                ('is_internal', models.BooleanField(default=True, help_text='True if owner is internal team member')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creatio_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('source', models.CharField(choices=[('meeting', 'Meeting Detection'), ('calendar', 'Calendar Import'), ('manual', 'Manual Entry'), ('crm_sync', 'CRM Sync'), ('email', 'Email'), ('web', 'Website'), ('referral', 'Referral'), ('other', 'Other')], default='meeting', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('opportunity', 'Opportunity'), ('customer', 'Customer'), ('lost', 'Lost'), ('disqualified', 'Disqualified')], default='new', max_length=20)),
                ('qualification_score', models.IntegerField(default=0, help_text='Lead qualification score (0-100)')),
                ('last_meeting_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_count', models.IntegerField(default=0)),
                ('relationship_stage', models.CharField(blank=True, choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('engaged', 'Engaged'), ('negotiating', 'Negotiating'), ('closing', 'Closing')], max_length=50, null=True)),
                ('decision_authority', models.CharField(choices=[('decision_maker', 'Decision Maker'), ('influencer', 'Influencer'), ('user', 'End User'), ('gatekeeper', 'Gatekeeper'), ('champion', 'Champion'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_close_date', models.DateField(blank=True, null=True)),
                ('probability', models.IntegerField(default=0, help_text='Win probability (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('general', 'General Note'), ('ai_insight', 'AI Insight')], default='general', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competitor_name', models.CharField(max_length=200)),
                ('competitive_context', models.TextField()),
                ('strengths_mentioned', models.JSONField(blank=True, default=list)),
                ('weaknesses_mentioned', models.JSONField(blank=True, default=list)),
                ('pricing_intelligence', models.JSONField(blank=True, default=dict)),
                ('relationship_status', models.CharField(choices=[('incumbent', 'Incumbent Vendor'), ('evaluating', 'Under Evaluation'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_intel', to='leads.lead')),
            ],
            options={
                'db_table': 'competitive_intelligence',
                'ordering': ['-created_at'],
            },
        ),
    ]
