# Generated by Django 4.2.7 on 2025-08-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveintelligence',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['lead', 'created_at'], name='lead_notes_lead_id_d6cc25_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['author', 'created_at'], name='lead_notes_author__cb526c_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['note_type'], name='lead_notes_note_ty_db68f6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_email_554d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'last_name'], name='leads_company_88a018_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to'], name='leads_status_f724a2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_meeting_date'], name='leads_last_me_16048c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['qualification_score'], name='leads_qualifi_0b8017_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['creatio_id'], name='leads_creatio_e211f3_idx'),
        ),
        migrations.AddIndex(
            model_name='competitiveintelligence',
            index=models.Index(fields=['lead', 'competitor_name'], name='competitive_lead_id_348dac_idx'),
        ),
        migrations.AddIndex(
            model_name='competitiveintelligence',
            index=models.Index(fields=['threat_level'], name='competitive_threat__127cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='competitiveintelligence',
            index=models.Index(fields=['relationship_status'], name='competitive_relatio_9333b5_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['meeting', 'status'], name='action_item_meeting_55fe46_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['owner_user', 'status'], name='action_item_owner_u_9965d9_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['due_date', 'status'], name='action_item_due_dat_64ae41_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['priority', 'status'], name='action_item_priorit_0188da_idx'),
        ),
    ]
