# Generated by Django 4.2.7 on 2025-08-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='notes_version',
            field=models.IntegerField(default=0),
        ),
    ]
