# Generated by Django 4.2.7 on 2025-08-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingsession_notes_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_session_id', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(max_length=50)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('connecting', 'Connecting'), ('connected', 'Connected'), ('transcribing', 'Transcribing'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connecting', max_length=50)),
                ('raw_transcript', models.TextField(blank=True)),
                ('speaker_mapping', models.JSONField(default=dict)),
                ('audio_quality', models.CharField(default='good', max_length=20)),
                ('error_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DraftSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_generated_summary', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('extracted_action_items', models.JSONField(default=list)),
                ('suggested_next_steps', models.JSONField(default=list)),
                ('decisions_made', models.JSONField(default=list)),
                ('suggested_crm_updates', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField()),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='actionitem',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='assignee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['priority', 'status'], name='meetings_ac_priorit_2d79dc_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['due_date'], name='meetings_ac_due_dat_40c75a_idx'),
        ),
        migrations.AddField(
            model_name='draftsummary',
            name='bot_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.callbotsession'),
        ),
        migrations.AddField(
            model_name='callbotsession',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting'),
        ),
        migrations.AddIndex(
            model_name='draftsummary',
            index=models.Index(fields=['confidence_score'], name='meetings_dr_confide_80d201_idx'),
        ),
        migrations.AddIndex(
            model_name='draftsummary',
            index=models.Index(fields=['created_at'], name='meetings_dr_created_51a11e_idx'),
        ),
        migrations.AddIndex(
            model_name='callbotsession',
            index=models.Index(fields=['join_time'], name='meetings_ca_join_ti_455d89_idx'),
        ),
        migrations.AddIndex(
            model_name='callbotsession',
            index=models.Index(fields=['connection_status'], name='meetings_ca_connect_2f5404_idx'),
        ),
        migrations.AddIndex(
            model_name='callbotsession',
            index=models.Index(fields=['platform'], name='meetings_ca_platfor_b49927_idx'),
        ),
    ]
