# Generated by Django 4.2.7 on 2025-08-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_callbotsession_draftsummary_actionitem_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_rep_email', models.EmailField(max_length=254)),
                ('validation_questions', models.JSONField(default=list)),
                ('rep_responses', models.JSONField(default=dict)),
                ('validated_summary', models.TextField(blank=True)),
                ('approved_crm_updates', models.JSONField(default=dict)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('changes_made', models.JSONField(default=list)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('draft_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.draftsummary')),
            ],
        ),
        migrations.CreateModel(
            name='CRMSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_system', models.CharField(choices=[('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('creatio', 'Creatio')], max_length=50)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=50)),
                ('crm_record_id', models.CharField(blank=True, max_length=200)),
                ('sync_payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.validationsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='validationsession',
            index=models.Index(fields=['validation_status'], name='meetings_va_validat_475e06_idx'),
        ),
        migrations.AddIndex(
            model_name='validationsession',
            index=models.Index(fields=['sales_rep_email'], name='meetings_va_sales_r_3c2c10_idx'),
        ),
        migrations.AddIndex(
            model_name='validationsession',
            index=models.Index(fields=['started_at'], name='meetings_va_started_95b7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='validationsession',
            index=models.Index(fields=['expires_at'], name='meetings_va_expires_d11f92_idx'),
        ),
        migrations.AddIndex(
            model_name='crmsyncrecord',
            index=models.Index(fields=['crm_system', 'sync_status'], name='meetings_cr_crm_sys_f710f6_idx'),
        ),
        migrations.AddIndex(
            model_name='crmsyncrecord',
            index=models.Index(fields=['sync_status'], name='meetings_cr_sync_st_264069_idx'),
        ),
        migrations.AddIndex(
            model_name='crmsyncrecord',
            index=models.Index(fields=['created_at'], name='meetings_cr_created_37612c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crmsyncrecord',
            unique_together={('validation_session', 'crm_system')},
        ),
    ]
