# Generated by Django 4.2.7 on 2025-08-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_validationsession_crmsyncrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('follow_up', 'Follow-up'), ('thank_you', 'Thank You'), ('next_steps', 'Next Steps'), ('meeting_summary', 'Meeting Summary'), ('action_items', 'Action Items')], default='follow_up', max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('cc_emails', models.JSONField(default=list)),
                ('bcc_emails', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('approval_requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.EmailField(blank=True, max_length=254)),
                ('rejection_reason', models.TextField(blank=True)),
                ('scheduled_send_time', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.validationsession')),
            ],
        ),
        migrations.AlterField(
            model_name='crmsyncrecord',
            name='crm_system',
            field=models.CharField(choices=[('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('creatio', 'Creatio'), ('sap_c4c', 'SAP C4C')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_email', models.EmailField(max_length=254)),
                ('approval_token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.draftemail')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='meetings_em_status_32d14e_idx'), models.Index(fields=['approver_email'], name='meetings_em_approve_eea0cb_idx'), models.Index(fields=['expires_at'], name='meetings_em_expires_c10f13_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='draftemail',
            index=models.Index(fields=['status'], name='meetings_dr_status_9b2e80_idx'),
        ),
        migrations.AddIndex(
            model_name='draftemail',
            index=models.Index(fields=['email_type'], name='meetings_dr_email_t_5aa668_idx'),
        ),
        migrations.AddIndex(
            model_name='draftemail',
            index=models.Index(fields=['scheduled_send_time'], name='meetings_dr_schedul_3512f7_idx'),
        ),
        migrations.AddIndex(
            model_name='draftemail',
            index=models.Index(fields=['created_at'], name='meetings_dr_created_e716c9_idx'),
        ),
    ]
