# Generated by Django 4.2.7 on 2025-08-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('exchange', 'Exchange Server')], max_length=20)),
                ('provider_event_id', models.CharField(max_length=200)),
                ('calendar_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('event_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('organizer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('attendees', models.JSONField(default=list, help_text='List of attendee information')),
                ('meeting_created', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField()),
                ('etag', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSyncStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('calendar_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=20)),
                ('last_sync_start', models.DateTimeField(blank=True, null=True)),
                ('last_sync_end', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('events_processed', models.IntegerField(default=0)),
                ('events_created', models.IntegerField(default=0)),
                ('events_updated', models.IntegerField(default=0)),
                ('events_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('sync_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_sync_status',
            },
        ),
    ]
