# Generated by Django 4.2.7 on 2025-08-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
        ('calendar_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calendarsyncstatus',
            index=models.Index(fields=['user', 'status'], name='calendar_sy_user_id_ed84e8_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsyncstatus',
            index=models.Index(fields=['last_successful_sync'], name='calendar_sy_last_su_bf386d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarsyncstatus',
            unique_together={('user', 'provider', 'calendar_id')},
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start_time'], name='calendar_ev_user_id_26e211_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['provider', 'calendar_id'], name='calendar_ev_provide_32a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['organizer_email'], name='calendar_ev_organiz_6de217_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['meeting_created'], name='calendar_ev_meeting_64886c_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_time', 'end_time'], name='calendar_ev_start_t_3d3f8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('provider', 'provider_event_id', 'user')},
        ),
    ]
