# Generated by Django 4.2.7 on 2025-08-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('meeting_id', models.IntegerField(db_index=True)),
                ('lead_context', models.JSONField(default=dict)),
                ('conversation_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='ai_assistan_session_d66375_idx'), models.Index(fields=['meeting_id'], name='ai_assistan_meeting_639b19_idx'), models.Index(fields=['is_active'], name='ai_assistan_is_acti_0b63bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('question_suggestion', 'Question Suggestion'), ('note_processing', 'Note Processing'), ('action_extraction', 'Action Item Extraction'), ('summary_generation', 'Summary Generation')], max_length=50)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.aisession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['interaction_type'], name='ai_assistan_interac_82bc40_idx'), models.Index(fields=['success'], name='ai_assistan_success_22f6b5_idx'), models.Index(fields=['created_at'], name='ai_assistan_created_35f3d5_idx')],
            },
        ),
    ]
