# Generated by Django 4.2.7 on 2025-08-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_event_id', models.CharField(max_length=200, unique=True)),
                ('calendar_provider', models.CharField(default='google', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('meeting_type', models.CharField(choices=[('discovery', 'Discovery Call'), ('demo', 'Product Demo'), ('negotiation', 'Negotiation'), ('follow_up', 'Follow-up'), ('closing', 'Closing Meeting'), ('internal', 'Internal Meeting'), ('other', 'Other')], default='other', max_length=50)),
                ('is_sales_meeting', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence that this is a sales meeting (0-1)')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('debriefing_scheduled', models.BooleanField(default=False)),
                ('debriefing_completed', models.BooleanField(default=False)),
                ('debriefing_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('participant_type', models.CharField(choices=[('organizer', 'Organizer'), ('required', 'Required Attendee'), ('optional', 'Optional Attendee'), ('resource', 'Resource')], default='required', max_length=20)),
                ('response_status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative'), ('no_response', 'No Response')], default='no_response', max_length=20)),
                ('is_external', models.BooleanField(default=True)),
                ('match_confidence', models.FloatField(default=0.0, help_text='Confidence score for lead matching (0-1)')),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_verification_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_participants',
                'indexes': [models.Index(fields=['email'], name='meeting_par_email_dda95f_idx'), models.Index(fields=['company', 'name'], name='meeting_par_company_60be4b_idx'), models.Index(fields=['matched_lead'], name='meeting_par_matched_a67983_idx'), models.Index(fields=['is_external', 'match_confidence'], name='meeting_par_is_exte_c4485c_idx')],
                'unique_together': {('meeting', 'email')},
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('note_type', models.CharField(default='general', max_length=50)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meeting', 'created_at'], name='meeting_not_meeting_d0b89f_idx'), models.Index(fields=['author', 'created_at'], name='meeting_not_author__b1abca_idx'), models.Index(fields=['note_type'], name='meeting_not_note_ty_33bc51_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time', 'organizer'], name='meetings_start_t_e70839_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['is_sales_meeting', 'meeting_type'], name='meetings_is_sale_3a3def_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['calendar_event_id'], name='meetings_calenda_d1f3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'start_time'], name='meetings_status_e9f4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['debriefing_scheduled', 'debriefing_completed'], name='meetings_debrief_dc05b5_idx'),
        ),
    ]
